// Mocks generated by Mockito 5.0.16 from annotations
// in quiz_proj/test/data/category/bloc/category_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:quiz_proj/data/category/model/category.dart' as _i3;
import 'package:quiz_proj/data/category/repository/category_repository.dart'
    as _i4;
import 'package:quiz_proj/data/category/source/category_source.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCategorySource_0 extends _i1.Fake implements _i2.CategorySource {}

class _FakeCategory_1 extends _i1.Fake implements _i3.Category {}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i4.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategorySource get categorySource =>
      (super.noSuchMethod(Invocation.getter(#categorySource),
          returnValue: _FakeCategorySource_0()) as _i2.CategorySource);
  @override
  _i5.Future<List<_i3.Category>> getCategories() =>
      (super.noSuchMethod(Invocation.method(#getCategories, []),
              returnValue: Future<List<_i3.Category>>.value(<_i3.Category>[]))
          as _i5.Future<List<_i3.Category>>);
  @override
  _i5.Future<_i3.Category> createCategory(_i3.Category? category) =>
      (super.noSuchMethod(Invocation.method(#createCategory, [category]),
              returnValue: Future<_i3.Category>.value(_FakeCategory_1()))
          as _i5.Future<_i3.Category>);
  @override
  _i5.Future<dynamic> deleteCategory(String? id) =>
      (super.noSuchMethod(Invocation.method(#deleteCategory, [id]),
          returnValue: Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  _i5.Future<_i3.Category> updateCategory(_i3.Category? category) =>
      (super.noSuchMethod(Invocation.method(#updateCategory, [category]),
              returnValue: Future<_i3.Category>.value(_FakeCategory_1()))
          as _i5.Future<_i3.Category>);
  @override
  String toString() => super.toString();
}
